### ISSUE TITLE
Failed to query Rancher Metadata (/self/host): 404 Client Error: Not Found

### ISSUE THREAD

**Issue by crunchtime-ali** [janeczku/datadog-rancher-init#1]
I've installed your image in Rancher via the template from the community catalog https://github.com/rancher/community-catalog/tree/master/templates/datadog

It is running on four host but two hosts always fail with the following error:

```
Querying Rancher Metadata API
Traceback (most recent call last):
  File "/opt/rancher/entrypoint-wrapper.py", line 166, in <module>
    main()
  File "/opt/rancher/entrypoint-wrapper.py", line 101, in main
    host = get_metadata('/self/host', TIMEOUT)
  File "/opt/rancher/entrypoint-wrapper.py", line 49, in get_metadata
    raise RuntimeError("Failed to query Rancher Metadata (%s): %s" % (path, str(e)))
RuntimeError: Failed to query Rancher Metadata (/self/host): 404 Client Error: Not Found
```

Do you know what could be causing this issue?

**Comment by crunchtime-ali** [comment]
The problem is the search path.
I created a PR which fixes the problem https://github.com/janeczku/datadog-rancher-init/pull/2

**Comment by janeczku** [comment]
Closed in https://github.com/janeczku/datadog-rancher-init/commit/c1e771a996dd75382be5c4dd60e6c541095c69aa
